/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadorasimple;

/**
 *
 * @author ederj
 */
public class ClaseVentana extends javax.swing.JFrame {

    /**
     * Creates new form ClaseVentana
     */
    public ClaseVentana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla = new javax.swing.JLabel();
        sieteBtn = new javax.swing.JButton();
        ochoBtn = new javax.swing.JButton();
        nueveBtn = new javax.swing.JButton();
        CuatroBtn = new javax.swing.JButton();
        cincoBtn = new javax.swing.JButton();
        seisBtn = new javax.swing.JButton();
        unoBtn = new javax.swing.JButton();
        DosBtn = new javax.swing.JButton();
        TresBtn = new javax.swing.JButton();
        ceroBtn = new javax.swing.JButton();
        puntoBtn = new javax.swing.JButton();
        IgualBtn = new javax.swing.JButton();
        sumaBtn = new javax.swing.JButton();
        RestaBtn = new javax.swing.JButton();
        MultiplicacionBtn = new javax.swing.JButton();
        DivisionBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantalla.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N

        sieteBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sieteBtn.setText("7");

        ochoBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ochoBtn.setText("8");
        ochoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoBtnActionPerformed(evt);
            }
        });

        nueveBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nueveBtn.setText("9");

        CuatroBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        CuatroBtn.setText("4");

        cincoBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cincoBtn.setText("5");

        seisBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        seisBtn.setText("6");
        seisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisBtnActionPerformed(evt);
            }
        });

        unoBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        unoBtn.setText("1");

        DosBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DosBtn.setText("2");
        DosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DosBtnActionPerformed(evt);
            }
        });

        TresBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TresBtn.setText("3");

        ceroBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ceroBtn.setText("0");

        puntoBtn.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        puntoBtn.setText(".");

        IgualBtn.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        IgualBtn.setText("=");

        sumaBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        sumaBtn.setText("Suma");
        sumaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaBtnActionPerformed(evt);
            }
        });

        RestaBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RestaBtn.setText("Resta");
        RestaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaBtnActionPerformed(evt);
            }
        });

        MultiplicacionBtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        MultiplicacionBtn.setText("Multiplicacion");

        DivisionBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DivisionBtn.setText("Division");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(unoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CuatroBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sieteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(puntoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ochoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ceroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IgualBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DivisionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nueveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(MultiplicacionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(cincoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TresBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sumaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RestaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TresBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sumaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CuatroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cincoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RestaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sieteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ochoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nueveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MultiplicacionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ceroBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(puntoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IgualBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DivisionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ochoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ochoBtnActionPerformed

    private void DosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DosBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DosBtnActionPerformed

    private void seisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seisBtnActionPerformed

    private void sumaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumaBtnActionPerformed

    private void RestaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RestaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClaseVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClaseVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClaseVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClaseVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClaseVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CuatroBtn;
    private javax.swing.JButton DivisionBtn;
    private javax.swing.JButton DosBtn;
    private javax.swing.JButton IgualBtn;
    private javax.swing.JButton MultiplicacionBtn;
    private javax.swing.JButton RestaBtn;
    private javax.swing.JButton TresBtn;
    private javax.swing.JButton ceroBtn;
    private javax.swing.JButton cincoBtn;
    private javax.swing.JButton nueveBtn;
    private javax.swing.JButton ochoBtn;
    private javax.swing.JLabel pantalla;
    private javax.swing.JButton puntoBtn;
    private javax.swing.JButton seisBtn;
    private javax.swing.JButton sieteBtn;
    private javax.swing.JButton sumaBtn;
    private javax.swing.JButton unoBtn;
    // End of variables declaration//GEN-END:variables
}
